CREATE TABLE _USER (ID  INT PRIMARY KEY, USER_NAME VARCHAR(25), MAIL VARCHAR(50), PASS VARCHAR(25));
CREATE TABLE TICKET (ID  INT PRIMARY KEY, TITRE VARCHAR(25), TICKET_DESCRIPTION VARCHAR(50), ID_USER INT, TICKET_STATUS VARCHAR(8), FOREIGN KEY(ID_USER) REFERENCES _USER(ID));

INSERT INTO _USER(ID,USER_NAME, MAIL, PASS) values (1,'prisca', 'prisca@gmail.com', 'prisca');
INSERT INTO TICKET (ID,TITRE, TICKET_DESCRIPTION,ID_USER, TICKET_STATUS) values (1,'titre', 'description', 1, 'En_cours');